version: '3.8'
services:
  api:
    container_name: node_api
    restart: on-failure
    depends_on:
      - mongo
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: on-failure
    ports:
      - 27017:27017

    

 